services:
  db:
    image: postgres:15-alpine
    container_name: pipeline_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "${DB_PORT_HOST}:${DB_PORT}"
    
  queue:
    image: rabbitmq:3.12-management-alpine
    container_name: pipeline_queue
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}" 
  cache:
    image: redis:7-alpine
    container_name: pipeline_cache
    ports:
        - "${REDIS_PORT}:${REDIS_PORT}"

volumes:
  postgres_data: